### ISSUE TITLE
can llvm-bolt tool, optimize bin to  BOLTed bin  with separate debug info file (DWARF)

### ISSUE THREAD

**Issue by zpget** [facebookincubator/BOLT#106]
I have a requirement. Can bolt tools consider to support optimized bin and debug info separation, user can choose  to separate or not
This has several advantages：
1. Reduce BOLTed bin size and speed up online
2. when online core , put  separate debug info file (DWARF) together with BOLTed bin to view core stack info

**Comment by rafaelauler** [comment]
If by debug separation you mean split dwarf, we are currently working on that.

If you just need to separate the DWARF info from the binary, you can still do that with standard striping tools (objcopy, strip etc) after BOLT processes the binary, otherwise the debug info will not reflect the new addresses.

**Comment by aaupov** [comment]
Split DWARF support has been added this year. Please check the recent BOLT version.
