### ISSUE TITLE
Instrumentation: watchProcess - Is there a reason to clear counters?

### ISSUE THREAD

**Issue by yota9** [facebookincubator/BOLT#121]
Hello!
The prof file is truncated each time it is opened, I would expect that the counters will be updated on each dump, but they are getting cleared each time they are getting dumped. Is the a reason for this or the clear could  be just removed?
Thank you!

**Comment by maksfb** [comment]
Do you mean the profile generated by instrumentation? If you have trouble with the file being overwritten on different invocations, use `-instrumentation-file-append-pid` option while instrumenting the binary and it should insert unique PID into the file name.

**Comment by yota9** [comment]
No, sorry. I mean that each time watchProcess() calls __bolt_instr_data_dump(). But since data dump is cycled and openProfile() opens output file with O_TRUNC the new data dump just overwrites old information. It's ok, but since  watchProcess also calls__bolt_instr_clear_counters() the old counters information becomes just wasted, I don't understand why it should happen. Thank you!

**Comment by rafaelauler** [comment]
Hi @yota9!

This is partially explained in the comments of "__bolt_instr_clear_counters": clearing the counters is used to allow us to instrument different phases of the services. Allow me to elaborate on that a little bit. During the start of a service, it will call a bunch of constructors and initializers that are called only once. If they have profile associated with them, BOLT will put them in the "hot" section*. To avoid unnecessarily bloating the hot section, the counters are reset to discard previous, unwanted profile. The idea here is that you will pass "--instrumentation-sleep-time=" with the duration of the profile collection. For example, if it is set to 120 seconds,  the profile will contain 2 minutes worth of profile and nothing more. These 2 minutes will be captured from the last time frame and initializers will not be included.

* BOLT treating every function with profile as hot deserves a discussion on its own. BOLT was created and optimized to work with sampled LBR profile. In the sampling world, anything with profile indicates that the function is probably running for a while and deserves attention from the cache layout perspective. Now, you might think that this is easily fixed by providing a "threshold" in which functions are considered hot or cold, and I anticipate that it is not as simple as that. We tried that and in fact we were never able to beat LBR profiles by using an instrumented profile which, in theory, is more complete. The recommended pipeline is to still use LBR if you can.

**Comment by yota9** [comment]
@rafaelauler Thank you for your answer! 
I was thinking about such possibilities too, but as from a user standpoint such behavior is not very clean, especially if we are speaking about short periods of time.  
I was just curious, so I don't insist, but might be we could just create numerable files like prof.fdata.1, prof.fdata.2 & etc every time we wake up? I Think it would be much more consistent IMHO. 
Thank you again!

**Comment by rafaelauler** [comment]
What about an option that doesn't clean the profile at all? Say "--instrumentation-reset-counters=false"?

**Comment by yota9** [comment]
@rafaelauler Actually I'm using exactly this option right now for own purposes :grin:
