### ISSUE TITLE
Why SymbolOrdering is always 1?

### ISSUE THREAD

**Issue by dongAxis** [facebookincubator/BOLT#136]
FYI

It is wired for me, why SymbolOrdering is always 1?
https://github.com/facebookincubator/BOLT/blob/01f471e7108f04b66fd7d3689f3cae3ec8ff6449/llvm.patch#L989

Thanks in advance.

**Comment by maksfb** [comment]
You are right. It's a bug that never manifested itself as we've never exercised the path that uses the symbol order.

Thanks for reporting!

**Comment by dongAxis** [comment]
> You are right. It's a bug that never manifested itself as we've never exercised the path that uses the symbol order.
> 
> Thanks for reporting!

Thanks for replying.  I have another question, could the same binary use both bolt and autofdo in product env?

**Comment by maksfb** [comment]
Yes, that's what you'd want for maximum performance. You will have to collect BOLT profile on a binary with AutoFDO applied. I.e. collect one profile for AutoFDO and another for BOLT. The good news is that you wouldn't have to rebuild the binary the 2nd time for BOLT.

**Comment by dongAxis** [comment]
> Yes, that's what you'd want for maximum performance. You will have to collect BOLT profile on a binary with AutoFDO applied. I.e. collect one profile for AutoFDO and another for BOLT. The good news is that you wouldn't have to rebuild the binary the 2nd time for BOLT.

Thanks for replying, my other question is if the binary has been applying the autofdo and bolt, and we have already collected the profile autofdo and bolt profile for this binary. Can both profiles apply to the next compilation?

**Comment by dongAxis** [comment]
> > Yes, that's what you'd want for maximum performance. You will have to collect BOLT profile on a binary with AutoFDO applied. I.e. collect one profile for AutoFDO and another for BOLT. The good news is that you wouldn't have to rebuild the binary the 2nd time for BOLT.
> 
> Thanks for replying, my other question is if the binary has been applying the autofdo and bolt, and we have already collected the profile autofdo and bolt profile for this binary. Can both profiles apply to the next compilation?

In addition, when we do the next compilation, the source code might have some changes.

**Comment by rafaelauler** [comment]
> Thanks for replying, my other question is if the binary has been applying the autofdo and bolt, and we have already collected the profile autofdo and bolt profile for this binary. Can both profiles apply to the next compilation?

Yes, you can reapply old autofdo and BOLT profiles to a new version of your binary, with some caveats I'll try to explain below.

If you change the autofdo profile but don't update BOLT profile, the binary that the compiler generates will likely be so different (because of different inlining decisions) that it will invalidate BOLT's profile almost entirely. You shouldn't do that. Either update both autofdo and bolt, in that order, or don't update them.

You can measure this effect by looking at the number of stale functions in BOLT logs, or % of invalid samples. Example:

BOLT-WARNING: 1450 (5.4% of all profiled) functions have invalid (possibly stale) profile. Use -report-stale to see the list.
BOLT-WARNING: 18480802160 out of 54140113294 samples in the binary (34.1%) belong to functions with invalid (possibly stale) profile.

That is saying that 34% of the profile is discarded because it belongs to functions that are now different in this version of the binary. So you will likely lose performance.

Now, in the scenario that you do not refresh any profile for a while, you will slowly start losing profile quality as the source code changes. AutoFDO will be a bit more resilient, because it relies on debug info. But BOLT relies on function names plus offsets, so if a function changes only a little bit, it will discard the profile for that entire function.

The big picture here is, whenever you write new code, you need to first expose it to a prod-like environment to observe how it behaves, so you can optimize it. Neither AutoFDO nor BOLT can do anything about new code if it has never been observed in prod and you don't have profile for that. Therefore, working with profile from a past generation of the binary will always lead to worse performance -- how much worse depends on how fast things are changing in the source code.

>  In addition, when we do the next compilation, the source code might have some changes.
  
That is fine. Again, depends on how much the code changed. As long as you don't update AutoFDO without updating BOLT, you should be working with a fairly good profile. Keep an eye in BOLT log (invalid profile), that will help you understand what's happening.

**Comment by dongAxis** [comment]
thanks for replying , I get it.
