### ISSUE TITLE
Emitting function alignment

### ISSUE THREAD

**Issue by yota9** [facebookincubator/BOLT#139]
Hello! 
I've got a few of questions about emitFunction() EmitCodeAlignment.
1. The BinaryFunction::MinAlign comment mentions the C++ ABI, could I please have a link to read about such limitations?
2. If BC has relocations we set MaxAlignBytes if it is above zero, should not it be something like 
`if (MaxAlignBytes >= BinaryFunction::MinAlign - 1)` instead?
Thank you!

**Comment by rafaelauler** [comment]
Regarding question 1, I don't actually have the context for this, perhaps @maksfb can comment on that.

Regarding question 2, `MaxAlignBytes` is not an alignment number, but rather the maximum number of NOP bytes that the streamer is allowed to insert in order to achieve a certain alignment. The actual alignment is provided by `Function.getAlignment()`. In the case that `getAlignment()` returns a value below `MinAlign`, that's not a problem because we already aligned it at `MinAlign` by calling `Streamer.emitCodeAlignment(BinaryFunction::MinAlign);` just before.

Therefore, we can't really compare `MaxAlignBytes` with an alignment number (`MinAlign`). But what is the meaning of `MaxAlignBytes` in this comparison against zero? In this context, `MaxAlignBytes` is being used to decide whether or not to align at all. So, if the aligner pass decides this function shouldn't be aligned, it is going to leave it at zero, so we won't try to align it (except for the minimum alignment, which is always emitted).

**Comment by maksfb** [comment]
I don't have a quote from C++ ABI at hand, but at least on Linux x86-64, the compiler-generated code uses the low bit of the function pointer to differentiate between invoking a regular function and a member function.

**Comment by yota9** [comment]
@rafaelauler I see, thank you for your answer! :)
