### ISSUE TITLE
[Question] Inliner restrictions

### ISSUE THREAD

**Issue by Pierre-vh** [facebookincubator/BOLT#162]
Hello,

I was looking at the inliner's source code, and I saw that it has some limitations. Most make sense to me, but why can't we access `%rsp` directly in non tail-calls?

Why is this restriction there, and what would it take to lift it?

One side question: Shouldn't the inliner be saving registers? For instance if we have some assembly like this:
```
<write "x" to r0>
<call Foo> // foo writes to r0 & will be inlined
<read from r0> // expects to read "x"
```
Or does the inliner expect that the compiler deals with that and saves/restores the registers (in the cc?)?

Thank you very much

**Comment by rafaelauler** [comment]
The inliner in BOLT is pretty restricted because we expect an FDO compiler with LTO to perform the bulk of inlining work. So our pipeline assumes a PGO/LTO compiler is running before BOLT and inlining hot call sites.

Then, BOLT currently performs some small adjustments, such as inlining a small function if it is an obvious improvement. That's where these restrictions come from, but they can indeed be lifted.

Accessing RSP indicates the callee is not that simple: it has a frame and we need to merge the callee frame to the caller's, and update debug info accordingly (frame unwinding instructions).

For the side question, yes, the callee is required to save the registers. The process of inlining it doesn't change much, we just remove the call, but the instructions are pretty much the same -- if it is being saved before inlining, it is being saved after it.
