### ISSUE TITLE
perf2bolt internal error for kernel data

### ISSUE THREAD

**Issue by mahmoodn** [facebookincubator/BOLT#88]
When I try to profile kernel data, `perf2bolt` throws an error about build-id.

```
$ perf record -e cycles:k -j any,k -a -o perf.data.kernel ./test
...
[ perf record: Captured and wrote 12.426 MB perf.data.kernel (29756 samples) ]
$ ../build/bin/perf2bolt  -p perf.data.kernel -o perf.fdata.kernel ./test
PERF2BOLT: Starting data aggregation job for perf.data.kernel
PERF2BOLT: spawning perf job to read branch events
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x800000, offset 0x400000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-INFO: pre-processing profile using perf data aggregator
BOLT-INFO: binary build-id is:     8edd43fbf5a6d895172d205a7248a814e3b07bb2
PERF2BOLT: spawning perf job to read buildid list
PERF2BOLT-ERROR: failed to match build-id from perf output. This indicates the input binary supplied for data aggregation is not the same recorded by perf when collecting profiling data, or there were no samples recorded for the binary. Use -ignore-build-id option to override.
```
That is weird because the version of perf and kernel matches and I have built bolt on this kernel.

```
$ perf --version
perf version 4.19.125
$ uname -r
4.19.125
```

If I collect user data as below, then there is no problem

```
$ perf record -e cycles:u -j any,u -a -o perf.data.user ./test
...
[ perf record: Captured and wrote 8.517 MB perf.data.user (20652 samples) ]
$ $ ../build/bin/perf2bolt  -p perf.data.user -o perf.fdata.user ./test
PERF2BOLT: Starting data aggregation job for perf.data.user
PERF2BOLT: spawning perf job to read branch events
PERF2BOLT: spawning perf job to read mem events
PERF2BOLT: spawning perf job to read process events
PERF2BOLT: spawning perf job to read task events
BOLT-INFO: Target architecture: x86_64
BOLT-INFO: first alloc address is 0x400000
BOLT-INFO: creating new program header table at address 0x800000, offset 0x400000
BOLT-INFO: enabling relocation mode
BOLT-INFO: enabling strict relocation mode for aggregation purposes
BOLT-INFO: pre-processing profile using perf data aggregator
BOLT-INFO: binary build-id is:     8edd43fbf5a6d895172d205a7248a814e3b07bb2
PERF2BOLT: spawning perf job to read buildid list
PERF2BOLT: matched build-id and file name
PERF2BOLT: waiting for perf mmap events collection to finish...
PERF2BOLT: parsing perf-script mmap events output
PERF2BOLT: waiting for perf task events collection to finish...
PERF2BOLT: parsing perf-script task events output
PERF2BOLT: input binary is associated with 1 PID(s)
PERF2BOLT: waiting for perf events collection to finish...
PERF2BOLT: parse branch events...
PERF2BOLT: read 16727 samples and 263593 LBR entries
PERF2BOLT: 3925 samples (19.0%) were ignored
PERF2BOLT: traces mismatching disassembled function contents: 2750 (1.1%)
PERF2BOLT: out of range traces involving unknown regions: 239779 (97.1%)
PERF2BOLT: processing branch events...
PERF2BOLT: wrote 21 objects and 0 memory objects to perf.fdata.user
```

Any idea about that. How can I debug more?
```

**Comment by rafaelauler** [comment]
Optimizing kernel code is currently unsupported at the moment.

**Comment by mahmoodn** [comment]
Thanks for the reply.
I had an idea to build a complete static file where all system libraries go into the binary. I did that for a simple program. However, perf2bolt looks for dynamic section and therefore it throws an error.
I don't know why dynamic section is mandatory for bolt. As I see the sections, the `.rela.text` exists in the binary.

**Comment by mahmoodn** [comment]
What if I use `perf record -e cycles -j any -a -o perf.data.all ./test` in order to collect both kernel and user data? I checked that in this perf data file, the build-id of application (test) as well as other system files exist.
I am also able to proceed with the llvm-bolt. However, I am not sure if the reordering algorithm actually works on the system files and not the user code in test binary.

I have to say for that, I recompiled linux kernel and glibc with --emit-relocs. Do you have any idea?

**Comment by rafaelauler** [comment]
If you collect profile for system code too (using the event cycles instead of cycles:u), what happens is that all activity in system code will be discarded by perf2bolt when aggregating.  perf2bolt acts as a data sanitizer because it opens the input binary you provided and assumes this is the only code that you will optimize. Any activity recorded by perf outside the boundaries of the input ELF file is discarded when perf2bolt finishes producing the profile, which means llvm-bolt will not see this information.

**Comment by mahmoodn** [comment]
If that is the case, the output and subsequent analyses of
```
perf record -e cycles:u -j any,u -a -o perf.data.user ./test
```
and
```
perf record -e cycles -j any -a -o perf.data.user ./test
```
Must be the same. The former only records user code. The latter records both user and kernel but further bolt commands discard the kernel data. Do you agree with that? Because I have some other evidences...

**Comment by rafaelauler** [comment]
Yes, that's the gist of it. However, if data quality is really important for you, you might notice that there are weird interactions that can cause unexpected small(ish) biases in the data collected with filtering (for example, filtering for events happening in user code only).

First of all, the LBR update is decoupled from the sampling event (cycles). You might want to experiment with another sampling event (i.e. ROB MISC EVENT.LBR INSERTS, br_inst_retired.near_taken:uppp) that is better synced with the LBR.

Things get trickier when you filter not only the sampling event but also the LBR. When you pass "any,u", the LBR hardware is configured to stop inserting entries if IP is in system code. Note that these (LBR registers) are always being updated while branches are being executed, and the event (cycles) is only configuring the timing when these registers will be sampled. If you think about it, there are a few ways in which this could go wrong if you are chasing the perfect, unbiased profile: again, synchronization issues between LBR inserts and the sampled event. However, I'm not going to assume we want that simply because the hardware itself is unable to give us unbiased samples, even if we ignore the LBR and look only at the IP distribution of hardware (performance counter) events. The severity of this event bias depends on the specific processor microarchitecture.

With that in mind and because the user has a degree of freedom in setting up how data collection is performed, I can think of a couple non-trivial side effects:
- using cycles but any,u  will cause a given path to be logged several times while code is running in kernel (event is being triggered, but the LBR is not being updated)
- using cycles:u with any,u will make you miss branches closer to a system call simply because the trigger event is not uniform anymore (but triggered only when in userland)

The take away here is, expect weird profile in code paths that have syscalls.
